<?php

/**
 *
 * @class CountriesTableSeeder
 *
 * @author Rahul Sharma <rahul.sharma@surmountsoft.in>
 *
 * @copyright 2021 SurmountSoft Pvt. Ltd. All rights reserved.
 */

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('countries')->truncate();
        $countries = [
            ['id' => 1, 'country' => 'Afghanistan', 'capital' => 'Kabul', 'title' => 'Afghanistan', 'country_code' => 'AF', 'currency_code' => 'AFN', 'currency_name' => 'Afghanistan Afghani'],
            ['id' => 10, 'country' => 'Argentina', 'capital' => 'Buenos Aires', 'title' => 'Argentina', 'country_code' => 'AR', 'currency_code' => 'ARS', 'currency_name' => 'Argentina Peso'],
            ['id' => 100, 'country' => 'Guatemala', 'capital' => 'Guatemala', 'title' => 'Guatemala', 'country_code' => 'GT', 'currency_code' => 'GTQ', 'currency_name' => 'Guatemala Quetzal'],
            ['id' => 101, 'country' => 'Guernsey', 'capital' => 'Saint Peter Port', 'title' => 'Guernsey', 'country_code' => 'GG', 'currency_code' => 'GGP', 'currency_name' => 'Guernsey Pound'],
            ['id' => 102, 'country' => 'Guinea', 'capital' => 'Conakry', 'title' => 'Guinea', 'country_code' => 'GN', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 103, 'country' => 'Guinea-Bissau', 'capital' => 'Bissau', 'title' => 'Guinea-Bissau', 'country_code' => 'GW', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 104, 'country' => 'Guyana', 'capital' => 'Georgetown', 'title' => 'Guyana', 'country_code' => 'GY', 'currency_code' => 'GYD', 'currency_name' => 'Guyana Dollar'],
            ['id' => 105, 'country' => 'Haiti', 'capital' => 'Port-au-Prince', 'title' => 'Haiti', 'country_code' => 'HT', 'currency_code' => 'HTG', 'currency_name' => 'Haitian gourde'],
            ['id' => 106, 'country' => 'Heard Island and McDonald Islands', 'capital' => '', 'title' => 'The Heard Island and McDonald Islands', 'country_code' => 'HM', 'currency_code' => 'AUD', 'currency_name' => 'Australia Dollar'],
            ['id' => 107, 'country' => 'Holy See (Vatican City)', 'capital' => 'Vatican City', 'title' => 'The Vatican City', 'country_code' => 'VA', 'currency_code' => 'EUR', 'currency_name' => 'Euro Member Countries'],
            ['id' => 108, 'country' => 'Honduras', 'capital' => 'Tegucigalpa', 'title' => 'Honduras', 'country_code' => 'HN', 'currency_code' => 'HNL', 'currency_name' => 'Honduras Lempira'],
            ['id' => 109, 'country' => 'Hong Kong (SAR)', 'capital' => '', 'title' => 'Xianggang', 'country_code' => 'HK', 'currency_code' => 'HKD', 'currency_name' => 'Hong Kong dollar'],
            ['id' => 11, 'country' => 'Armenia', 'capital' => 'Yerevan', 'title' => 'Armenia', 'country_code' => 'AM', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 110, 'country' => 'Howland Island', 'capital' => '', 'title' => 'Howland Island', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 111, 'country' => 'Hungary', 'capital' => 'Budapest', 'title' => 'Hungary', 'country_code' => 'HU', 'currency_code' => 'HUF', 'currency_name' => 'Hungary Forint'],
            ['id' => 112, 'country' => 'Iceland', 'capital' => 'Reykjavik', 'title' => 'Iceland', 'country_code' => 'IS', 'currency_code' => 'ISK', 'currency_name' => 'Iceland Krona'],
            ['id' => 113, 'country' => 'India', 'capital' => 'New Delhi', 'title' => 'India', 'country_code' => 'IN', 'currency_code' => 'INR', 'currency_name' => 'India Rupee'],
            ['id' => 114, 'country' => 'Indonesia', 'capital' => 'Jakarta', 'title' => 'Indonesia', 'country_code' => 'ID', 'currency_code' => 'IDR', 'currency_name' => 'Indonesia Rupiah'],
            ['id' => 115, 'country' => 'Iran', 'capital' => 'Tehran', 'title' => 'Iran', 'country_code' => 'IR', 'currency_code' => 'IRR', 'currency_name' => 'Iran Rial'],
            ['id' => 116, 'country' => 'Iraq', 'capital' => 'Baghdad', 'title' => 'Iraq', 'country_code' => 'IQ', 'currency_code' => 'IQD', 'currency_name' => 'Iraqi dinar'],
            ['id' => 117, 'country' => 'Ireland', 'capital' => 'Dublin', 'title' => 'Ireland', 'country_code' => 'IE', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['id' => 118, 'country' => 'Israel', 'capital' => 'Jerusalem', 'title' => 'Israel', 'country_code' => 'IL', 'currency_code' => 'ILS', 'currency_name' => 'Israeli new shekel'],
            ['id' => 119, 'country' => 'Italy', 'capital' => 'Rome', 'title' => 'Italia', 'country_code' => 'IT', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['id' => 12, 'country' => 'Aruba', 'capital' => 'Oranjestad', 'title' => 'Aruba', 'country_code' => 'AW', 'currency_code' => 'AWG', 'currency_name' => 'Aruba Guilder'],
            ['id' => 120, 'country' => 'Jamaica', 'capital' => 'Kingston', 'title' => 'Jamaica', 'country_code' => 'JM', 'currency_code' => 'JMD', 'currency_name' => 'Jamaican dollar'],
            ['id' => 121, 'country' => 'Jan Mayen', 'capital' => '', 'title' => 'Jan Mayen', 'country_code' => 'SJ', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian krone'],
            ['id' => 122, 'country' => 'Japan', 'capital' => 'Tokyo', 'title' => 'Japan', 'country_code' => 'JP', 'currency_code' => 'JPY', 'currency_name' => 'Japan Yen'],
            ['id' => 123, 'country' => 'Jarvis Island', 'capital' => '', 'title' => 'Jarvis Island', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 124, 'country' => 'Jersey', 'capital' => 'Saint Helier', 'title' => 'Jersey', 'country_code' => 'JE', 'currency_code' => 'JEP', 'currency_name' => 'Jersey Pound'],
            ['id' => 125, 'country' => 'Johnston Atoll', 'capital' => '', 'title' => 'Johnston Atoll', 'country_code' => '', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar'],
            ['id' => 126, 'country' => 'Jordan', 'capital' => 'Amman', 'title' => 'Jordan', 'country_code' => 'JO', 'currency_code' => 'JOD', 'currency_name' => 'Jordanian dinar'],
            ['id' => 127, 'country' => 'Juan de Nova Island', 'capital' => '', 'title' => 'Juan de Nova Island', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 128, 'country' => 'Kazakhstan', 'capital' => 'Astana', 'title' => 'Kazakhstan', 'country_code' => 'KZ', 'currency_code' => 'KZT', 'currency_name' => 'Kazakhstan Tenge'],
            ['id' => 129, 'country' => 'Kenya', 'capital' => 'Nairobi', 'title' => 'Kenya', 'country_code' => 'KE', 'currency_code' => 'KES', 'currency_name' => 'Kenyan shilling'],
            ['id' => 13, 'country' => 'Ashmore and Cartier', 'capital' => '', 'title' => 'Ashmore and Cartier', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 130, 'country' => 'Kingman Reef', 'capital' => '', 'title' => 'Kingman Reef', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 131, 'country' => 'Kiribati', 'capital' => 'Tarawa', 'title' => 'Kiribati', 'country_code' => 'KI', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 132, 'country' => 'Korea, North', 'capital' => 'P\'yongyang', 'title' => 'North Korea', 'country_code' => 'KP', 'currency_code' => 'KPW', 'currency_name' => 'Korea (North) Won'],
            ['id' => 133, 'country' => 'Korea, South', 'capital' => 'Seoul', 'title' => 'South Korea', 'country_code' => 'KR', 'currency_code' => 'KRW', 'currency_name' => 'Korea (South) Won'],
            ['id' => 134, 'country' => 'Kuwait', 'capital' => 'Kuwait', 'title' => 'Al Kuwayt', 'country_code' => 'KW', 'currency_code' => 'KUD', 'currency_name' => 'Kuwaiti dinar'],
            ['id' => 135, 'country' => 'Kyrgyzstan', 'capital' => 'Bishkek', 'title' => 'Kyrgyzstan', 'country_code' => 'KG', 'currency_code' => 'KGS', 'currency_name' => 'Kyrgyzstani som'],
            ['id' => 136, 'country' => 'Laos', 'capital' => 'Vientiane', 'title' => 'Laos', 'country_code' => 'LA', 'currency_code' => 'LAK', 'currency_name' => 'Lao kip'],
            ['id' => 137, 'country' => 'Latvia', 'capital' => 'Riga', 'title' => 'Latvia', 'country_code' => 'LV', 'currency_code' => 'LVL', 'currency_name' => 'Latvia Lat'],
            ['id' => 138, 'country' => 'Lebanon', 'capital' => 'Beirut', 'title' => 'Lebanon', 'country_code' => 'LB', 'currency_code' => 'LBP', 'currency_name' => 'Lebanese pound'],
            ['id' => 139, 'country' => 'Lesotho', 'capital' => 'Maseru', 'title' => 'Lesotho', 'country_code' => 'LS', 'currency_code' => 'LSL', 'currency_name' => 'Loti'],
            ['id' => 14, 'country' => 'Australia', 'capital' => 'Canberra', 'title' => 'Australia', 'country_code' => 'AU', 'currency_code' => 'AUD', 'currency_name' => 'Australian dollar'],
            ['id' => 140, 'country' => 'Liberia', 'capital' => 'Monrovia', 'title' => 'Liberia', 'country_code' => 'LR', 'currency_code' => 'LRD', 'currency_name' => 'Liberia Dollar'],
            ['id' => 141, 'country' => 'Libya', 'capital' => 'Tripoli', 'title' => 'Libya', 'country_code' => 'LY', 'currency_code' => 'LYD', 'currency_name' => 'Libyan dinar'],
            ['id' => 142, 'country' => 'Liechtenstein', 'capital' => 'Vaduz', 'title' => 'Liechtenstein', 'country_code' => 'LI', 'currency_code' => 'CHF', 'currency_name' => 'Switzerland Franc'],
            ['id' => 143, 'country' => 'Lithuania', 'capital' => 'Vilnius', 'title' => 'Lithuania', 'country_code' => 'LT', 'currency_code' => 'LTL', 'currency_name' => 'Lithuania Litas'],
            ['id' => 144, 'country' => 'Luxembourg', 'capital' => 'Luxembourg', 'title' => 'Luxembourg', 'country_code' => 'LU', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 145, 'country' => 'Macau', 'capital' => '', 'title' => 'Macau', 'country_code' => 'MO', 'currency_code' => 'MOP', 'currency_name' => 'Macanese pataca'],
            ['id' => 146, 'country' => 'Macedonia, The Former Yugoslav Republic of', 'capital' => 'Skopje', 'title' => 'Makedonija', 'country_code' => 'MK', 'currency_code' => 'MKD', 'currency_name' => 'Macedonia Denar'],
            ['id' => 147, 'country' => 'Madagascar', 'capital' => 'Antananarivo', 'title' => 'Madagascar', 'country_code' => 'MG', 'currency_code' => 'MGA', 'currency_name' => 'Malagasy ariary'],
            ['id' => 148, 'country' => 'Malawi', 'capital' => 'Lilongwe', 'title' => 'Malawi', 'country_code' => 'MW', 'currency_code' => 'MWK', 'currency_name' => 'Malawian kwacha'],
            ['id' => 149, 'country' => 'Malaysia', 'capital' => 'Kuala Lumpur', 'title' => 'Malaysia', 'country_code' => 'MY', 'currency_code' => 'MYR', 'currency_name' => 'Malaysian ringgit'],
            ['id' => 15, 'country' => 'Austria', 'capital' => 'Vienna', 'title' => 'Austria', 'country_code' => 'AT', 'currency_code' => 'ATS', 'currency_name' => 'Euro'],
            ['id' => 150, 'country' => 'Maldives', 'capital' => 'Male', 'title' => 'Maldives', 'country_code' => 'MV', 'currency_code' => 'MVR', 'currency_name' => 'Maldivian rufiyaa'],
            ['id' => 151, 'country' => 'Mali', 'capital' => 'Bamako', 'title' => 'Mali', 'country_code' => 'ML', 'currency_code' => '', 'currency_name' => 'West African CFA franc'],
            ['id' => 152, 'country' => 'Malta', 'capital' => 'Valletta', 'title' => 'Malta', 'country_code' => 'MT', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 153, 'country' => 'Man, Isle of', 'capital' => 'Douglas', 'title' => 'The Isle of Man', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 154, 'country' => 'Marshall Islands', 'capital' => 'Majuro', 'title' => 'The Marshall Islands', 'country_code' => 'MH', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 155, 'country' => 'Martinique', 'capital' => 'Fort-de-France', 'title' => 'Martinique', 'country_code' => 'MQ', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 156, 'country' => 'Mauritania', 'capital' => 'Nouakchott', 'title' => 'Mauritania', 'country_code' => 'MR', 'currency_code' => 'MRU', 'currency_name' => 'Mauritanian ouguiya'],
            ['id' => 157, 'country' => 'Mauritius', 'capital' => 'Port Louis', 'title' => 'Mauritius', 'country_code' => 'MU', 'currency_code' => 'MUR', 'currency_name' => 'Mauritian rupee'],
            ['id' => 158, 'country' => 'Mayotte', 'capital' => 'Mamoutzou', 'title' => 'Mayotte', 'country_code' => 'YT', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 159, 'country' => 'Mexico', 'capital' => 'Mexico', 'title' => 'Mexico', 'country_code' => 'MX', 'currency_code' => 'MXN', 'currency_name' => 'Mexican peso'],
            ['id' => 16, 'country' => 'Azerbaijan', 'capital' => 'Baku (Baki)', 'title' => 'Azerbaijan', 'country_code' => 'AZ', 'currency_code' => 'AZN', 'currency_name' => 'Azerbaijan New Manat'],
            ['id' => 160, 'country' => 'Micronesia, Federated States of', 'capital' => 'Palikir', 'title' => 'The Federated States of Micronesia', 'country_code' => 'FM', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 161, 'country' => 'Midway Islands', 'capital' => '', 'title' => 'The Midway Islands', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 162, 'country' => 'Miscellaneous (French)', 'capital' => '', 'title' => 'Miscellaneous (French)', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 163, 'country' => 'Moldova', 'capital' => 'Chisinau', 'title' => 'Moldova', 'country_code' => 'MD', 'currency_code' => 'MDL', 'currency_name' => 'Moldovan leu'],
            ['id' => 164, 'country' => 'Monaco', 'capital' => 'Monaco', 'title' => 'Monaco', 'country_code' => 'MC', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 165, 'country' => 'Mongolia', 'capital' => 'Ulaanbaatar', 'title' => 'Mongolia', 'country_code' => 'MN', 'currency_code' => 'MNT', 'currency_name' => 'Mongolia Tughrik'],
            ['id' => 166, 'country' => 'Montenegro', 'capital' => '', 'title' => 'Montenegro', 'country_code' => 'ME', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 167, 'country' => 'Montserrat', 'capital' => 'Plymouth', 'title' => 'Montserrat', 'country_code' => 'MS', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar'],
            ['id' => 168, 'country' => 'Morocco', 'capital' => 'Rabat', 'title' => 'Morocco', 'country_code' => 'MA', 'currency_code' => 'MAD', 'currency_name' => 'Moroccan dirham'],
            ['id' => 169, 'country' => 'Mozambique', 'capital' => 'Maputo', 'title' => 'Mozambique', 'country_code' => 'MZ', 'currency_code' => 'MZN', 'currency_name' => 'Mozambican metical'],
            ['id' => 17, 'country' => 'The Bahamas', 'capital' => 'Nassau', 'title' => 'The Bahamas', 'country_code' => 'BS', 'currency_code' => 'BSD', 'currency_name' => 'Bahamian dollar'],
            ['id' => 170, 'country' => 'Myanmar', 'capital' => '', 'title' => 'Myanmar', 'country_code' => 'MM', 'currency_code' => 'MMK', 'currency_name' => 'Burmese kyat'],
            ['id' => 171, 'country' => 'Namibia', 'capital' => 'Windhoek', 'title' => 'Namibia', 'country_code' => 'NA', 'currency_code' => 'NAD', 'currency_name' => 'Namibian Dollar'],
            ['id' => 172, 'country' => 'Nauru', 'capital' => '', 'title' => 'Nauru', 'country_code' => 'NR', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 173, 'country' => 'Navassa Island', 'capital' => '', 'title' => 'Navassa Island', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 174, 'country' => 'Nepal', 'capital' => 'Kathmandu', 'title' => 'Nepal', 'country_code' => 'NP', 'currency_code' => 'NPR', 'currency_name' => 'Nepalese rupee'],
            ['id' => 175, 'country' => 'Netherlands', 'capital' => 'Amsterdam', 'title' => 'The Netherlands', 'country_code' => 'NL', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 176, 'country' => 'Netherlands Antilles', 'capital' => 'Willemstad', 'title' => 'The Netherlands Antilles', 'country_code' => 'AN', 'currency_code' => 'ANG', 'currency_name' => 'Netherlands Antilles Guilder'],
            ['id' => 177, 'country' => 'New Caledonia', 'capital' => 'Noumea', 'title' => 'New Caledonia', 'country_code' => 'NC', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 178, 'country' => 'New Zealand', 'capital' => 'Wellington', 'title' => 'New Zealand', 'country_code' => 'NZ', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand dollar'],
            ['id' => 179, 'country' => 'Nicaragua', 'capital' => 'Managua', 'title' => 'Nicaragua', 'country_code' => 'NI', 'currency_code' => 'NIO', 'currency_name' => 'Nicaraguan córdoba'],
            ['id' => 18, 'country' => 'Bahrain', 'capital' => 'Manama', 'title' => 'Bahrain', 'country_code' => 'BH', 'currency_code' => 'BHD', 'currency_name' => 'Bahraini dinar'],
            ['id' => 180, 'country' => 'Niger', 'capital' => 'Niamey', 'title' => 'Niger', 'country_code' => 'NE', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 181, 'country' => 'Nigeria', 'capital' => 'Abuja', 'title' => 'Nigeria', 'country_code' => 'NG', 'currency_code' => 'NGN', 'currency_name' => 'Nigerian naira'],
            ['id' => 182, 'country' => 'Niue', 'capital' => 'Alofi', 'title' => 'Niue', 'country_code' => 'NU', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 183, 'country' => 'Norfolk Island', 'capital' => 'Kingston', 'title' => 'Norfolk Island', 'country_code' => 'NF', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 184, 'country' => 'Northern Mariana Islands', 'capital' => 'Saipan', 'title' => 'The Northern Mariana Islands', 'country_code' => 'MP', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 185, 'country' => 'Norway', 'capital' => 'Oslo', 'title' => 'Norway', 'country_code' => 'NO', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian krone'],
            ['id' => 186, 'country' => 'Oman', 'capital' => 'Muscat', 'title' => 'Oman', 'country_code' => 'OM', 'currency_code' => 'OMR', 'currency_name' => 'Omani rial'],
            ['id' => 187, 'country' => 'Pakistan', 'capital' => 'Islamabad', 'title' => 'Pakistan', 'country_code' => 'PK', 'currency_code' => 'PKR', 'currency_name' => 'Pakistan Rupee'],
            ['id' => 188, 'country' => 'Palau', 'capital' => 'Koror', 'title' => 'Palau', 'country_code' => 'PW', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 189, 'country' => 'Palmyra Atoll', 'capital' => '', 'title' => 'Palmyra Atoll', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 19, 'country' => 'Baker Island', 'capital' => '', 'title' => 'Baker Island', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 190, 'country' => 'Panama', 'capital' => 'Panama', 'title' => 'Panama', 'country_code' => 'PA', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 191, 'country' => 'Papua New Guinea', 'capital' => 'Port Moresby', 'title' => 'Papua New Guinea', 'country_code' => 'PG', 'currency_code' => 'PGK', 'currency_name' => 'Papua New Guinean kina'],
            ['id' => 192, 'country' => 'Paracel Islands', 'capital' => '', 'title' => 'The Paracel Islands', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 193, 'country' => 'Paraguay', 'capital' => 'Asuncion', 'title' => 'Paraguay', 'country_code' => 'PY', 'currency_code' => 'PYG', 'currency_name' => 'Paraguayan guaraní'],
            ['id' => 194, 'country' => 'Peru', 'capital' => 'Lima', 'title' => 'Peru', 'country_code' => 'PE', 'currency_code' => 'PEN', 'currency_name' => 'Sol'],
            ['id' => 195, 'country' => 'Philippines', 'capital' => 'Manila', 'title' => 'The Philippines', 'country_code' => 'PH', 'currency_code' => 'PHP', 'currency_name' => 'Philippine peso'],
            ['id' => 196, 'country' => 'Pitcairn Islands', 'capital' => 'Adamstown', 'title' => 'The Pitcairn Islands', 'country_code' => 'PN', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand dollar'],
            ['id' => 197, 'country' => 'Poland', 'capital' => 'Warsaw', 'title' => 'Poland', 'country_code' => 'PL', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 198, 'country' => 'Portugal', 'capital' => 'Lisbon', 'title' => 'Portugal', 'country_code' => 'PT', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 199, 'country' => 'Puerto Rico', 'capital' => 'San Juan', 'title' => 'Puerto Rico', 'country_code' => 'PR', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 2, 'country' => 'Albania', 'capital' => 'Tirana', 'title' => 'Albania', 'country_code' => 'AL', 'currency_code' => 'ALL', 'currency_name' => 'Albania Lek'],
            ['id' => 20, 'country' => 'Bangladesh', 'capital' => 'Dhaka', 'title' => 'Bangladesh', 'country_code' => 'BD', 'currency_code' => 'BDT', 'currency_name' => 'Bangladeshi taka'],
            ['id' => 200, 'country' => 'Qatar', 'capital' => 'Doha', 'title' => 'Qatar', 'country_code' => 'QA', 'currency_code' => 'QAR', 'currency_name' => 'Qatari riyal'],
            ['id' => 201, 'country' => 'RÃ©union', 'capital' => 'Saint-Denis', 'title' => 'RÃ©union', 'country_code' => 'RE', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 202, 'country' => 'Romania', 'capital' => 'Bucharest', 'title' => 'Romania', 'country_code' => 'RO', 'currency_code' => 'RON', 'currency_name' => 'Romanian leu'],
            ['id' => 203, 'country' => 'Russia', 'capital' => 'Moscow', 'title' => 'Russia', 'country_code' => 'RU', 'currency_code' => 'RUB', 'currency_name' => 'Russian ruble'],
            ['id' => 204, 'country' => 'Rwanda', 'capital' => 'Kigali', 'title' => 'Rwanda', 'country_code' => 'RW', 'currency_code' => 'RWF', 'currency_name' => 'Rwandan franc'],
            ['id' => 205, 'country' => 'Saint Helena', 'capital' => 'Jamestown', 'title' => 'Saint Helena', 'country_code' => 'SH', 'currency_code' => 'SHP', 'currency_name' => 'Saint Helena pound'],
            ['id' => 206, 'country' => 'Saint Kitts and Nevis', 'capital' => 'Basseterre', 'title' => 'Saint Kitts and Nevis', 'country_code' => 'KN', 'currency_code' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar'],
            ['id' => 207, 'country' => 'Saint Lucia', 'capital' => 'Castries', 'title' => 'Saint Lucia', 'country_code' => 'LC', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 208, 'country' => 'Saint Pierre and Miquelon', 'capital' => 'Saint-Pierre', 'title' => 'Saint Pierre and Miquelon', 'country_code' => 'PM', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 209, 'country' => 'Saint Vincent and the Grenadines', 'capital' => 'Kingstown', 'title' => 'Saint Vincent and the Grenadines', 'country_code' => 'VC', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 21, 'country' => 'Barbados', 'capital' => 'Bridgetown', 'title' => 'Barbados', 'country_code' => 'BB', 'currency_code' => 'BBD', 'currency_name' => 'Barbadian dollar'],
            ['id' => 210, 'country' => 'Samoa', 'capital' => 'Apia', 'title' => 'Samoa', 'country_code' => 'WS', 'currency_code' => 'WST', 'currency_name' => 'Samoan tala'],
            ['id' => 211, 'country' => 'San Marino', 'capital' => 'San Marino', 'title' => 'San Marino', 'country_code' => 'SM', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 212, 'country' => 'S?o TomÃ© and Pr?ncipe', 'capital' => 'Sao Tome', 'title' => 'S?o TomÃ© and Pr?ncipe', 'country_code' => 'ST', 'currency_code' => 'STN', 'currency_name' => 'São Tomé and Príncipe dobra'],
            ['id' => 213, 'country' => 'Saudi Arabia', 'capital' => 'Riyadh', 'title' => 'Saudi Arabia', 'country_code' => 'SA', 'currency_code' => 'SR', 'currency_name' => 'Saudi riyal'],
            ['id' => 214, 'country' => 'Senegal', 'capital' => 'Dakar', 'title' => 'Senegal', 'country_code' => 'SN', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 215, 'country' => 'Serbia', 'capital' => '', 'title' => 'Serbia', 'country_code' => 'RS', 'currency_code' => 'RSD', 'currency_name' => 'Serbian dinar'],
            ['id' => 216, 'country' => 'Serbia and Montenegro', 'capital' => '', 'title' => 'Serbia and Montenegro', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 217, 'country' => 'Seychelles', 'capital' => 'Victoria', 'title' => 'Seychelles', 'country_code' => 'SC', 'currency_code' => 'SCR', 'currency_name' => 'Seychellois rupee'],
            ['id' => 218, 'country' => 'Sierra Leone', 'capital' => 'Freetown', 'title' => 'Sierra Leone', 'country_code' => 'SL', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 219, 'country' => 'Singapore', 'capital' => 'Singapore', 'title' => 'Singapore', 'country_code' => 'SG', 'currency_code' => 'SGD', 'currency_name' => 'Singapore dollar'],
            ['id' => 22, 'country' => 'Bassas da India', 'capital' => '', 'title' => 'Bassas da India', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 220, 'country' => 'Slovakia', 'capital' => 'Bratislava', 'title' => 'Slovakia', 'country_code' => 'SK', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 221, 'country' => 'Slovenia', 'capital' => 'Ljubljana', 'title' => 'Slovenia', 'country_code' => 'SI', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 222, 'country' => 'Solomon Islands', 'capital' => 'Honiara', 'title' => 'The Solomon Islands', 'country_code' => 'SB', 'currency_code' => 'SBD', 'currency_name' => 'Solomon Islands dollar'],
            ['id' => 223, 'country' => 'Somalia', 'capital' => 'Mogadishu', 'title' => 'Somalia', 'country_code' => 'SO', 'currency_code' => 'SOS', 'currency_name' => 'Somali shilling'],
            ['id' => 224, 'country' => 'South Africa', 'capital' => 'Pretoria', 'title' => 'South Africa', 'country_code' => 'ZA', 'currency_code' => 'ZAR', 'currency_name' => 'South African rand'],
            ['id' => 225, 'country' => 'South Georgia and the South Sandwich Islands', 'capital' => '', 'title' => 'The South Georgia and the South Sandwich Islands', 'country_code' => 'GS', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 226, 'country' => 'Spain', 'capital' => 'Madrid', 'title' => 'Spain', 'country_code' => 'ES', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 227, 'country' => 'Spratly Islands', 'capital' => '', 'title' => 'The Spratly Islands', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 228, 'country' => 'Sri Lanka', 'capital' => 'Colombo', 'title' => 'Sri Lanka', 'country_code' => 'LK', 'currency_code' => 'LKR', 'currency_name' => 'Sri Lankan rupee'],
            ['id' => 229, 'country' => 'Sudan', 'capital' => 'Khartoum', 'title' => 'Sudan', 'country_code' => 'SD', 'currency_code' => 'SDD', 'currency_name' => 'Sudanese pound'],
            ['id' => 23, 'country' => 'Belarus', 'capital' => 'Minsk', 'title' => 'Belarus', 'country_code' => 'BY', 'currency_code' => 'BYN', 'currency_name' => 'Belarusian ruble'],
            ['id' => 230, 'country' => 'Suriname', 'capital' => 'Paramaribo', 'title' => 'Suriname', 'country_code' => 'SR', 'currency_code' => 'SRD', 'currency_name' => 'Surinamese dollar'],
            ['id' => 231, 'country' => 'Svalbard', 'capital' => 'Longyearbyen', 'title' => 'Svalbard', 'country_code' => 'SJ', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 232, 'country' => 'Swaziland', 'capital' => 'Mbabane', 'title' => 'Swaziland', 'country_code' => 'SZ', 'currency_code' => 'SZL', 'currency_name' => 'Swazi lilangeni'],
            ['id' => 233, 'country' => 'Sweden', 'capital' => 'Stockholm', 'title' => 'Sweden', 'country_code' => 'SE', 'currency_code' => 'SEK', 'currency_name' => 'Swedish krona'],
            ['id' => 234, 'country' => 'Switzerland', 'capital' => 'Bern', 'title' => 'Switzerland', 'country_code' => 'CH', 'currency_code' => 'CHF', 'currency_name' => 'Swiss franc'],
            ['id' => 235, 'country' => 'Syria', 'capital' => 'Damascus', 'title' => 'Syria', 'country_code' => 'SY', 'currency_code' => 'SYP', 'currency_name' => 'Syrian pound'],
            ['id' => 236, 'country' => 'Taiwan', 'capital' => 'Taipei', 'title' => 'Taiwan', 'country_code' => 'TW', 'currency_code' => 'TWD', 'currency_name' => 'New Taiwan dollar'],
            ['id' => 237, 'country' => 'Tajikistan', 'capital' => 'Dushanbe', 'title' => 'Tajikistan', 'country_code' => 'TJ', 'currency_code' => 'TJS', 'currency_name' => 'Tajikistani somoni'],
            ['id' => 238, 'country' => 'Tanzania', 'capital' => 'Dar es Salaam', 'title' => 'Tanzania', 'country_code' => 'TZ', 'currency_code' => 'TZS', 'currency_name' => 'Tanzanian shilling'],
            ['id' => 239, 'country' => 'Thailand', 'capital' => 'Bangkok', 'title' => 'Thailand', 'country_code' => 'TH', 'currency_code' => 'THB', 'currency_name' => 'Baht'],
            ['id' => 24, 'country' => 'Belgium', 'capital' => 'Brussels', 'title' => 'Belgium', 'country_code' => 'BE', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 240, 'country' => 'Togo', 'capital' => 'Lome', 'title' => 'Togo', 'country_code' => 'TG', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 241, 'country' => 'Tokelau', 'capital' => '', 'title' => 'Tokelau', 'country_code' => 'TK', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 242, 'country' => 'Tonga', 'capital' => 'Nuku\'alofa', 'title' => 'Tonga', 'country_code' => 'TO', 'currency_code' => 'TOP', 'currency_name' => 'Tongan pa anga'],
            ['id' => 243, 'country' => 'Trinidad and Tobago', 'capital' => 'Port-of-Spain', 'title' => 'Trinidad and Tobago', 'country_code' => 'TT', 'currency_code' => 'TTD', 'currency_name' => 'Trinidad and Tobago dollar'],
            ['id' => 244, 'country' => 'Tromelin Island', 'capital' => '', 'title' => 'Tromelin Island', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 245, 'country' => 'Tunisia', 'capital' => 'Tunis', 'title' => 'Tunisia', 'country_code' => 'TN', 'currency_code' => 'TND', 'currency_name' => 'Tunisian dinar'],
            ['id' => 246, 'country' => 'Turkey', 'capital' => 'Ankara', 'title' => 'Turkey', 'country_code' => 'TR', 'currency_code' => 'TRY', 'currency_name' => 'Turkish lira'],
            ['id' => 247, 'country' => 'Turkmenistan', 'capital' => 'Ashgabat', 'title' => 'Turkmenistan', 'country_code' => 'TM', 'currency_code' => 'TMT', 'currency_name' => 'Turkmenistan manat'],
            ['id' => 248, 'country' => 'Turks and Caicos Islands', 'capital' => 'Cockburn Town', 'title' => 'The Turks and Caicos Islands', 'country_code' => 'TC', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 249, 'country' => 'Tuvalu', 'capital' => 'Funafuti', 'title' => 'Tuvalu', 'country_code' => 'TV', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 25, 'country' => 'Belize', 'capital' => 'Belmopan', 'title' => 'Belize', 'country_code' => 'BZ', 'currency_code' => 'BZD', 'currency_name' => 'Belize dollar'],
            ['id' => 250, 'country' => 'Uganda', 'capital' => 'Kampala', 'title' => 'Uganda', 'country_code' => 'UG', 'currency_code' => 'UGX', 'currency_name' => 'Ugandan shilling'],
            ['id' => 251, 'country' => 'Ukraine', 'capital' => 'Kiev', 'title' => 'The Ukraine', 'country_code' => 'UA', 'currency_code' => 'UAH', 'currency_name' => 'Ukrainian hryvnia'],
            ['id' => 252, 'country' => 'United Arab Emirates', 'capital' => 'Abu Dhabi', 'title' => 'The United Arab Emirates', 'country_code' => 'AE', 'currency_code' => 'AED', 'currency_name' => 'United Arab Emirates dirham'],
            ['id' => 253, 'country' => 'United Kingdom', 'capital' => 'London', 'title' => 'The United Kingdom', 'country_code' => 'GB', 'currency_code' => 'GBP', 'currency_name' => 'Pound sterling'],
            ['id' => 254, 'country' => 'United States', 'capital' => 'Washington, DC', 'title' => 'The United States', 'country_code' => 'US', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar'],
            ['id' => 255, 'country' => 'United States Minor Outlying Islands', 'capital' => '', 'title' => 'The United States Minor Outlying Islands', 'country_code' => 'UM', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar'],
            ['id' => 256, 'country' => 'Uruguay', 'capital' => 'Montevideo', 'title' => 'Uruguay', 'country_code' => 'UY', 'currency_code' => 'UYU', 'currency_name' => 'Uruguayan peso'],
            ['id' => 257, 'country' => 'Uzbekistan', 'capital' => 'Tashkent', 'title' => 'Uzbekistan', 'country_code' => 'UZ', 'currency_code' => 'UZS', 'currency_name' => 'Uzbekistani som'],
            ['id' => 258, 'country' => 'Vanuatu', 'capital' => 'Port-Vila', 'title' => 'Vanuatu', 'country_code' => 'VU', 'currency_code' => 'VUV', 'currency_name' => 'Vanuatu vatu'],
            ['id' => 259, 'country' => 'Venezuela', 'capital' => 'Caracas', 'title' => 'Venezuela', 'country_code' => 'VE', 'currency_code' => 'VES', 'currency_name' => 'bolívar soberano'],
            ['id' => 26, 'country' => 'Benin', 'capital' => 'Porto-Novo', 'title' => 'Benin', 'country_code' => 'BJ', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 260, 'country' => 'Vietnam', 'capital' => 'Hanoi', 'title' => 'Vietnam', 'country_code' => 'VN', 'currency_code' => 'VND', 'currency_name' => 'Vietnamese dong'],
            ['id' => 261, 'country' => 'Virgin Islands', 'capital' => 'Charlotte Amalie', 'title' => 'The Virgin Islands', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 262, 'country' => 'Virgin Islands (UK)', 'capital' => '', 'title' => 'Virgin Islands (UK)', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 263, 'country' => 'Virgin Islands (US)', 'capital' => '', 'title' => 'Virgin Islands (US)', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 264, 'country' => 'Wake Island', 'capital' => '', 'title' => 'Wake Island', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 265, 'country' => 'Wallis and Futuna', 'capital' => 'Mata-Utu', 'title' => 'Wallis and Futuna', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 266, 'country' => 'West Bank', 'capital' => '', 'title' => 'The West Bank', 'country_code' => 'IL', 'currency_code' => 'ILS', 'currency_name' => 'Israeli new shekel'],
            ['id' => 267, 'country' => 'Western Sahara', 'capital' => '', 'title' => 'Western Sahara', 'country_code' => 'EH', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 268, 'country' => 'Western Samoa', 'capital' => '', 'title' => 'Western Samoa', 'country_code' => 'WS', 'currency_code' => 'WST', 'currency_name' => 'Samoan tala'],
            ['id' => 269, 'country' => 'World', 'capital' => '', 'title' => 'The World', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 27, 'country' => 'Bermuda', 'capital' => 'Hamilton', 'title' => 'Bermuda', 'country_code' => 'BM', 'currency_code' => 'BMD', 'currency_name' => 'Bermudian dollar'],
            ['id' => 270, 'country' => 'Yemen', 'capital' => 'Sanaa', 'title' => 'Yemen', 'country_code' => 'YE', 'currency_code' => 'YER', 'currency_name' => 'Yemeni rial'],
            ['id' => 271, 'country' => 'Yugoslavia', 'capital' => 'Belgrade', 'title' => 'Yugoslavia', 'country_code' => 'YU', 'currency_code' => 'YUG', 'currency_name' => 'Yugoslav dinar'],
            ['id' => 272, 'country' => 'Zaire', 'capital' => '', 'title' => 'Zaire', 'country_code' => 'ZR', 'currency_code' => 'ZRN', 'currency_name' => 'Zairean zaire'],
            ['id' => 273, 'country' => 'Zambia', 'capital' => 'Lusaka', 'title' => 'Zambia', 'country_code' => 'ZM', 'currency_code' => 'ZMW', 'currency_name' => 'Zambian kwacha'],
            ['id' => 274, 'country' => 'Zimbabwe', 'capital' => 'Harare', 'title' => 'Zimbabwe', 'country_code' => 'ZW', 'currency_code' => 'ZWD', 'currency_name' => 'Zimbabwean Dollar'],
            ['id' => 275, 'country' => 'Palestinian Territory, Occupied', 'capital' => '', 'title' => 'Palestine', 'country_code' => 'PS', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 28, 'country' => 'Bhutan', 'capital' => 'Thimphu', 'title' => 'Bhutan', 'country_code' => 'BT', 'currency_code' => 'BTN', 'currency_name' => 'ngultrum'],
            ['id' => 29, 'country' => 'Bolivia', 'capital' => 'La Paz /Sucre', 'title' => 'Bolivia', 'country_code' => 'BO', 'currency_code' => 'BOB', 'currency_name' => 'Bolivian boliviano'],
            ['id' => 3, 'country' => 'Algeria', 'capital' => 'Algiers', 'title' => 'Algeria', 'country_code' => 'DZ', 'currency_code' => 'DZD', 'currency_name' => 'Algerian dinar'],
            ['id' => 30, 'country' => 'Bosnia and Herzegovina', 'capital' => 'Sarajevo', 'title' => 'Bosnia and Herzegovina', 'country_code' => 'BA', 'currency_code' => 'BAM', 'currency_name' => 'Bosnia and Herzegovina convertible mark'],
            ['id' => 31, 'country' => 'Botswana', 'capital' => 'Gaborone', 'title' => 'Botswana', 'country_code' => 'BW', 'currency_code' => 'BWP', 'currency_name' => 'Botswana pula'],
            ['id' => 32, 'country' => 'Bouvet Island', 'capital' => '', 'title' => 'Bouvet Island', 'country_code' => 'BV', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian krone'],
            ['id' => 33, 'country' => 'Brazil', 'capital' => 'Brasilia', 'title' => 'Brazil', 'country_code' => 'BR', 'currency_code' => 'BRL', 'currency_name' => 'Brazilian real'],
            ['id' => 34, 'country' => 'British Indian Ocean Territory', 'capital' => '', 'title' => 'The British Indian Ocean Territory', 'country_code' => 'IO', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 35, 'country' => 'British Virgin Islands', 'capital' => 'Road Town', 'title' => 'The British Virgin Islands', 'country_code' => 'VG', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 36, 'country' => 'Brunei Darussalam', 'capital' => '', 'title' => 'Brunei', 'country_code' => 'BN', 'currency_code' => 'BND', 'currency_name' => 'Brunei dollar'],
            ['id' => 37, 'country' => 'Bulgaria', 'capital' => 'Sofia', 'title' => 'Bulgaria', 'country_code' => 'BG', 'currency_code' => 'BGN', 'currency_name' => 'Bulgarian lev'],
            ['id' => 38, 'country' => 'Burkina Faso', 'capital' => 'Ouagadougou', 'title' => 'Burkina Faso', 'country_code' => 'BF', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 39, 'country' => 'Burma', 'capital' => 'Rangoon', 'title' => 'Burma', 'country_code' => 'MM', 'currency_code' => 'MMK', 'currency_name' => 'Burmese kyat'],
            ['id' => 4, 'country' => 'American Samoa', 'capital' => 'Pago Pago', 'title' => 'American Samoa', 'country_code' => 'AS', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 40, 'country' => 'Burundi', 'capital' => 'Bujumbura', 'title' => 'Burundi', 'country_code' => 'BI', 'currency_code' => 'BIF', 'currency_name' => 'Burundian franc'],
            ['id' => 41, 'country' => 'Cambodia', 'capital' => 'Phnom Penh', 'title' => 'Cambodia', 'country_code' => 'KH', 'currency_code' => 'KHR', 'currency_name' => 'Cambodian riel'],
            ['id' => 42, 'country' => 'Cameroon', 'capital' => 'Yaounde', 'title' => 'Cameroon', 'country_code' => 'CM', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 43, 'country' => 'Canada', 'capital' => 'Ottawa', 'title' => 'Canada', 'country_code' => 'CA', 'currency_code' => 'CAD', 'currency_name' => 'Canadian dollar'],
            ['id' => 44, 'country' => 'Cape Verde', 'capital' => 'Praia', 'title' => 'Cape Verde', 'country_code' => 'CV', 'currency_code' => 'CVE', 'currency_name' => 'Cape Verdean escudo'],
            ['id' => 45, 'country' => 'Cayman Islands', 'capital' => 'George Town', 'title' => 'The Cayman Islands', 'country_code' => 'KY', 'currency_code' => 'KYD', 'currency_name' => 'Cayman Islands dollar'],
            ['id' => 46, 'country' => 'Central African Republic', 'capital' => 'Bangui', 'title' => 'The Central African Republic', 'country_code' => 'CF', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 47, 'country' => 'Chad', 'capital' => 'N\'Djamena', 'title' => 'Chad', 'country_code' => 'TD', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 48, 'country' => 'Chile', 'capital' => 'Santiago', 'title' => 'Chile', 'country_code' => 'CL', 'currency_code' => 'CLP', 'currency_name' => 'Chile'],
            ['id' => 49, 'country' => 'China', 'capital' => 'Beijing', 'title' => 'China', 'country_code' => 'CN', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 5, 'country' => 'Andorra', 'capital' => 'Andorra la Vella', 'title' => 'Andorra', 'country_code' => 'AD', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 50, 'country' => 'Christmas Island', 'capital' => 'The Settlement', 'title' => 'Christmas Island', 'country_code' => 'CX', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 51, 'country' => 'Clipperton Island', 'capital' => '', 'title' => 'Clipperton Island', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 52, 'country' => 'Cocos (Keeling) Islands', 'capital' => 'West Island', 'title' => 'The Cocos Islands', 'country_code' => 'CC', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 53, 'country' => 'Colombia', 'capital' => 'Bogota', 'title' => 'Colombia', 'country_code' => 'CO', 'currency_code' => 'COP', 'currency_name' => 'Colombian peso'],
            ['id' => 54, 'country' => 'Comoros', 'capital' => 'Moroni', 'title' => 'Comoros', 'country_code' => 'KM', 'currency_code' => 'KMF', 'currency_name' => 'Comorian franc'],
            ['id' => 55, 'country' => 'Congo, Democratic Republic of the Congo', 'capital' => 'Kinshasa', 'title' => 'Democratic Republic of the Congo', 'country_code' => 'CD', 'currency_code' => 'CDF', 'currency_name' => 'Congolese franc'],
            ['id' => 56, 'country' => 'Congo, Republic of the Congo', 'capital' => 'Brazzaville', 'title' => 'Republic of the Congo', 'country_code' => 'CG', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 57, 'country' => 'Cook Islands', 'capital' => 'Avarua', 'title' => 'The Cook Islands', 'country_code' => 'CK', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 58, 'country' => 'Coral Sea Islands', 'capital' => '', 'title' => 'The Coral Sea Islands', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 59, 'country' => 'Costa Rica', 'capital' => 'San Jose', 'title' => 'Costa Rica', 'country_code' => 'CR', 'currency_code' => 'CRC', 'currency_name' => 'Costa Rican colón'],
            ['id' => 6, 'country' => 'Angola', 'capital' => 'Luanda', 'title' => 'Angola', 'country_code' => 'AO', 'currency_code' => 'AOA', 'currency_name' => 'Angolan kwanza'],
            ['id' => 60, 'country' => 'Cote d\'Ivoire', 'capital' => 'Yamoussoukro', 'title' => 'Cote d\'Ivoire', 'country_code' => 'CI', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 61, 'country' => 'Croatia', 'capital' => 'Zagreb', 'title' => 'Croatia', 'country_code' => 'HR', 'currency_code' => 'HRK', 'currency_name' => 'Croatian kuna'],
            ['id' => 62, 'country' => 'Cuba', 'capital' => 'Havana', 'title' => 'Cuba', 'country_code' => 'CU', 'currency_code' => 'CUP', 'currency_name' => 'Cuban peso, Cuban convertible peso'],
            ['id' => 63, 'country' => 'Cyprus', 'capital' => 'Nicosia', 'title' => 'Cyprus', 'country_code' => 'CY', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 64, 'country' => 'Czech Republic', 'capital' => 'Prague', 'title' => 'The Czech Republic', 'country_code' => 'CZ', 'currency_code' => 'CZK', 'currency_name' => 'Czech koruna'],
            ['id' => 65, 'country' => 'Denmark', 'capital' => 'Copenhagen', 'title' => 'Denmark', 'country_code' => 'DK', 'currency_code' => 'DKK', 'currency_name' => 'Danish krone'],
            ['id' => 66, 'country' => 'Djibouti', 'capital' => 'Djibouti', 'title' => 'Djibouti', 'country_code' => 'DJ', 'currency_code' => 'DJF', 'currency_name' => 'Djiboutian franc'],
            ['id' => 67, 'country' => 'Dominica', 'capital' => 'Roseau', 'title' => 'Dominica', 'country_code' => 'DM', 'currency_code' => 'DOP', 'currency_name' => 'Dominican peso'],
            ['id' => 68, 'country' => 'Dominican Republic', 'capital' => 'Santo Domingo', 'title' => 'The Dominican Republic', 'country_code' => 'DO', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 69, 'country' => 'East Timor', 'capital' => 'Dili', 'title' => 'East Timor', 'country_code' => 'TP', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 7, 'country' => 'Anguilla', 'capital' => 'The Valley', 'title' => 'Anguilla', 'country_code' => 'AI', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 70, 'country' => 'Ecuador', 'capital' => 'Quito', 'title' => 'Ecuador', 'country_code' => 'EC', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 71, 'country' => 'Egypt', 'capital' => 'Cairo', 'title' => 'Egypt', 'country_code' => 'EG', 'currency_code' => 'EGP', 'currency_name' => 'Egyptian pound'],
            ['id' => 72, 'country' => 'El Salvador', 'capital' => 'San Salvador', 'title' => 'El Salvador', 'country_code' => 'SV', 'currency_code' => 'SVC', 'currency_name' => ''],
            ['id' => 73, 'country' => 'Equatorial Guinea', 'capital' => 'Malabo', 'title' => 'Equatorial Guinea', 'country_code' => 'GQ', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 74, 'country' => 'Eritrea', 'capital' => 'Asmara', 'title' => 'Eritrea', 'country_code' => 'ER', 'currency_code' => 'ERN', 'currency_name' => 'Eritrean nakfa'],
            ['id' => 75, 'country' => 'Estonia', 'capital' => 'Tallinn', 'title' => 'Estonia', 'country_code' => 'EE', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 76, 'country' => 'Ethiopia', 'capital' => 'Addis Ababa', 'title' => 'Ethiopia', 'country_code' => 'ET', 'currency_code' => 'ETB', 'currency_name' => 'Ethiopian birr'],
            ['id' => 77, 'country' => 'Europa Island', 'capital' => '', 'title' => 'Europa Island', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 78, 'country' => 'Falkland Islands (Islas Malvinas)', 'capital' => 'Stanley', 'title' => 'The Falkland Islands', 'country_code' => 'FK', 'currency_code' => 'FKP', 'currency_name' => 'Falkland Islands pound'],
            ['id' => 79, 'country' => 'Faroe Islands', 'capital' => 'Torshavn', 'title' => 'The Faroe Islands', 'country_code' => 'FO', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 8, 'country' => 'Antarctica', 'capital' => '', 'title' => 'Antarctica', 'country_code' => 'AQ', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 80, 'country' => 'Fiji', 'capital' => 'Suva', 'title' => 'Fiji', 'country_code' => 'FJ', 'currency_code' => 'FJD', 'currency_name' => 'Fijian dollar'],
            ['id' => 81, 'country' => 'Finland', 'capital' => 'Helsinki', 'title' => 'Finland', 'country_code' => 'FI', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 82, 'country' => 'France', 'capital' => 'Paris', 'title' => 'France', 'country_code' => 'FR', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 83, 'country' => 'France, Metropolitan', 'capital' => '', 'title' => 'Metropolitan France', 'country_code' => 'FX', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 84, 'country' => 'French Guiana', 'capital' => 'Cayenne', 'title' => 'French Guiana', 'country_code' => 'GF', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 85, 'country' => 'French Polynesia', 'capital' => 'Papeete', 'title' => 'French Polynesia', 'country_code' => 'PF', 'currency_code' => 'XPF', 'currency_name' => 'CFP franc'],
            ['id' => 86, 'country' => 'French Southern and Antarctic Lands', 'capital' => '', 'title' => 'The French Southern and Antarctic Lands', 'country_code' => 'TF', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 87, 'country' => 'Gabon', 'capital' => 'Libreville', 'title' => 'Gabon', 'country_code' => 'GA', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 88, 'country' => 'The Gambia', 'capital' => 'Banjul', 'title' => 'The Gambia', 'country_code' => 'GM', 'currency_code' => 'GMD', 'currency_name' => 'Gambian dalasi'],
            ['id' => 89, 'country' => 'Gaza Strip', 'capital' => '', 'title' => 'The Gaza Strip', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 9, 'country' => 'Antigua and Barbuda', 'capital' => 'Saint John\'s', 'title' => 'Antigua and Barbuda', 'country_code' => 'AG', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 90, 'country' => 'Georgia', 'capital' => 'T\'bilisi', 'title' => 'Georgia', 'country_code' => 'GE', 'currency_code' => 'GEL', 'currency_name' => 'Georgian lari'],
            ['id' => 91, 'country' => 'Germany', 'capital' => 'Berlin', 'title' => 'Deutschland', 'country_code' => 'DE', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 92, 'country' => 'Ghana', 'capital' => 'Accra', 'title' => 'Ghana', 'country_code' => 'GH', 'currency_code' => 'GHS', 'currency_name' => 'Ghanaian cedi'],
            ['id' => 93, 'country' => 'Gibraltar', 'capital' => 'Gibraltar', 'title' => 'Gibraltar', 'country_code' => 'GI', 'currency_code' => 'GIP', 'currency_name' => 'Gibraltar pound'],
            ['id' => 94, 'country' => 'Glorioso Islands', 'capital' => '', 'title' => 'The Glorioso Islands', 'country_code' => '', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 95, 'country' => 'Greece', 'capital' => 'Athens', 'title' => 'Greece', 'country_code' => 'GR', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 96, 'country' => 'Greenland', 'capital' => 'Nuuk', 'title' => 'Greenland', 'country_code' => 'GL', 'currency_code' => 'DKK', 'currency_name' => 'Danish krone'],
            ['id' => 97, 'country' => 'Grenada', 'capital' => 'Saint George\'s', 'title' => 'Grenada', 'country_code' => 'GD', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 98, 'country' => 'Guadeloupe', 'capital' => 'Basse-Terre', 'title' => 'Guadeloupe', 'country_code' => 'GP', 'currency_code' => '', 'currency_name' => ''],
            ['id' => 99, 'country' => 'Guam', 'capital' => 'Hagatna', 'title' => 'Guam', 'country_code' => 'GU', 'currency_code' => '', 'currency_name' => ''],
        ];
        \DB::table('countries')->insert($countries);
    }
}